import { 
  ITopic, 
  ICard, 
  ISeo, 
  Difficulty, 
  TopicType, 
  SubmitType, 
  CardGame,
  CardStatus,
  Status
} from '../models';

export const mockTopic: ITopic = {
  _id: 'topic-1',
  name: 'English Grammar',
  description: 'Learn essential English grammar rules',
  appId: 'app-1',
  questionNum: 10,
  slug: 'english-grammar',
  difficulty: Difficulty.MEDIUM,
  type: TopicType.TOPIC_TYPE_LESSON,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  orderIndex: 1,
};

export const mockExercise: ITopic = {
  _id: 'exercise-1',
  name: 'Present Simple Tense Quiz',
  description: 'Test your knowledge of present simple tense',
  appId: 'app-1',
  parentId: 'topic-1',
  questionNum: 5,
  slug: 'present-simple-quiz',
  difficulty: Difficulty.EASY,
  type: TopicType.TOPIC_TYPE_EXERCISE,
  submitType: SubmitType.CHECK_ON_ANSWER,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
  orderIndex: 1,
};

export const mockQuizCards: ICard[] = [
  {
    _id: 'card-1',
    topicId: 'exercise-1',
    question: {
      text: 'She _____ to school every day.',
      image: null,
      audio: null,
    },
    explanation: 'We use "goes" because the subject is third person singular (she).',
    explanationLang: {},
    explanationDefaultLang: 'en',
    difficulty: Difficulty.EASY,
    status: CardStatus.ACTIVE,
    choices: [
      { id: 1, textId: 'choice-1', content: 'go', isCorrect: false },
      { id: 2, textId: 'choice-2', content: 'goes', isCorrect: true },
      { id: 3, textId: 'choice-3', content: 'going', isCorrect: false },
      { id: 4, textId: 'choice-4', content: 'went', isCorrect: false },
    ],
    mapLangChoice: {},
    defaultChoiceLang: 'en',
    cardGame: CardGame.QUIZ,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    _id: 'card-2',
    topicId: 'exercise-1',
    question: {
      text: 'They _____ football on weekends.',
      image: null,
      audio: null,
    },
    explanation: 'We use "play" because the subject is plural (they).',
    explanationLang: {},
    explanationDefaultLang: 'en',
    difficulty: Difficulty.EASY,
    status: CardStatus.ACTIVE,
    choices: [
      { id: 1, textId: 'choice-1', content: 'plays', isCorrect: false },
      { id: 2, textId: 'choice-2', content: 'play', isCorrect: true },
      { id: 3, textId: 'choice-3', content: 'playing', isCorrect: false },
      { id: 4, textId: 'choice-4', content: 'played', isCorrect: false },
    ],
    mapLangChoice: {},
    defaultChoiceLang: 'en',
    cardGame: CardGame.QUIZ,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    _id: 'card-3',
    topicId: 'exercise-1',
    question: {
      text: 'I _____ coffee every morning.',
      image: null,
      audio: null,
    },
    explanation: 'We use "drink" with the subject "I".',
    explanationLang: {},
    explanationDefaultLang: 'en',
    difficulty: Difficulty.EASY,
    status: CardStatus.ACTIVE,
    choices: [
      { id: 1, textId: 'choice-1', content: 'drinks', isCorrect: false },
      { id: 2, textId: 'choice-2', content: 'drink', isCorrect: true },
      { id: 3, textId: 'choice-3', content: 'drinking', isCorrect: false },
      { id: 4, textId: 'choice-4', content: 'drank', isCorrect: false },
    ],
    mapLangChoice: {},
    defaultChoiceLang: 'en',
    cardGame: CardGame.QUIZ,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockSeo: ISeo = {
  _id: 'seo-1',
  slug: 'present-simple-quiz',
  title: 'Present Simple Tense Quiz - Test Your English Grammar',
  description: 'Practice present simple tense with interactive quiz questions',
  keyword: 'present simple, english grammar, quiz, test',
  imageSharing: {
    url: 'https://example.com/image.jpg',
  },
  imageSharingMeta: {
    title: 'Present Simple Quiz',
    alt: 'English Grammar Quiz',
    caption: 'Test your knowledge',
    description: 'Interactive quiz',
  },
  headerScript: '',
  bodyScript: '',
  metaRobot: 1,
  titleH1: 'Present Simple Tense Quiz',
  appId: 'app-1',
  summary: 'Test your understanding of present simple tense',
  content: '',
  jsonLd: [],
  locale: 'en',
  seo301: '',
  status: Status.ACTIVE,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
};

export const mockSpellingCards: ICard[] = [
  {
    _id: 'spelling-card-1',
    topicId: 'exercise-1',
    question: {
      text: 'Fill in the blanks with the correct form of the verb:',
      image: null,
      audio: null,
    },
    explanation: 'Practice using correct verb forms in sentences.',
    explanationLang: {},
    explanationDefaultLang: 'en',
    difficulty: Difficulty.MEDIUM,
    status: CardStatus.ACTIVE,
    choices: [],
    mapLangChoice: {},
    defaultChoiceLang: 'en',
    cardGame: CardGame.SPELLING,
    childCards: [
      {
        _id: 'spelling-child-1',
        topicId: 'exercise-1',
        question: {
          text: 'She _____ (go) to the market every Sunday.',
          image: null,
          audio: null,
        },
        explanation: 'The correct answer is "goes"',
        explanationLang: {},
        explanationDefaultLang: 'en',
        difficulty: Difficulty.MEDIUM,
        status: CardStatus.ACTIVE,
        parentId: 'spelling-card-1',
        choices: [
          { id: 1, textId: 'answer-1', content: 'goes', isCorrect: true },
        ],
        mapLangChoice: {},
        defaultChoiceLang: 'en',
        cardGame: CardGame.SPELLING,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-01-01'),
      },
      {
        _id: 'spelling-child-2',
        topicId: 'exercise-1',
        question: {
          text: 'They _____ (study) English every day.',
          image: null,
          audio: null,
        },
        explanation: 'The correct answer is "study"',
        explanationLang: {},
        explanationDefaultLang: 'en',
        difficulty: Difficulty.MEDIUM,
        status: CardStatus.ACTIVE,
        parentId: 'spelling-card-1',
        choices: [
          { id: 1, textId: 'answer-1', content: 'study', isCorrect: true },
        ],
        mapLangChoice: {},
        defaultChoiceLang: 'en',
        cardGame: CardGame.SPELLING,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-01-01'),
      },
    ],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockParaGameCards: ICard[] = [
  {
    _id: 'para-card-1',
    topicId: 'exercise-1',
    question: {
      text: 'Read the paragraph and answer the questions:',
      image: null,
      audio: null,
    },
    explanation: 'This paragraph tests your reading comprehension.',
    explanationLang: {},
    explanationDefaultLang: 'en',
    difficulty: Difficulty.HARD,
    status: CardStatus.ACTIVE,
    choices: [],
    mapLangChoice: {},
    defaultChoiceLang: 'en',
    cardGame: CardGame.PARA,
    childCards: [
      {
        _id: 'para-child-1',
        topicId: 'exercise-1',
        question: {
          text: 'What does Sarah do every morning?',
          image: null,
          audio: null,
        },
        explanation: 'Sarah goes jogging every morning.',
        explanationLang: {},
        explanationDefaultLang: 'en',
        difficulty: Difficulty.HARD,
        status: CardStatus.ACTIVE,
        parentId: 'para-card-1',
        choices: [
          { id: 1, textId: 'choice-1', content: 'She goes jogging', isCorrect: true },
          { id: 2, textId: 'choice-2', content: 'She goes swimming', isCorrect: false },
          { id: 3, textId: 'choice-3', content: 'She goes shopping', isCorrect: false },
          { id: 4, textId: 'choice-4', content: 'She stays home', isCorrect: false },
        ],
        mapLangChoice: {},
        defaultChoiceLang: 'en',
        cardGame: CardGame.QUIZ,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-01-01'),
      },
      {
        _id: 'para-child-2',
        topicId: 'exercise-1',
        question: {
          text: 'How often does she exercise?',
          image: null,
          audio: null,
        },
        explanation: 'She exercises every day.',
        explanationLang: {},
        explanationDefaultLang: 'en',
        difficulty: Difficulty.HARD,
        status: CardStatus.ACTIVE,
        parentId: 'para-card-1',
        choices: [
          { id: 1, textId: 'choice-1', content: 'Once a week', isCorrect: false },
          { id: 2, textId: 'choice-2', content: 'Every day', isCorrect: true },
          { id: 3, textId: 'choice-3', content: 'Twice a week', isCorrect: false },
          { id: 4, textId: 'choice-4', content: 'Never', isCorrect: false },
        ],
        mapLangChoice: {},
        defaultChoiceLang: 'en',
        cardGame: CardGame.QUIZ,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-01-01'),
      },
    ],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockSiblingTopics: ITopic[] = [
  {
    _id: 'exercise-2',
    name: 'Past Simple Tense Quiz',
    description: 'Test your knowledge of past simple tense',
    appId: 'app-1',
    parentId: 'topic-1',
    questionNum: 5,
    slug: 'past-simple-quiz',
    difficulty: Difficulty.MEDIUM,
    type: TopicType.TOPIC_TYPE_EXERCISE,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    orderIndex: 2,
  },
];

